resources:
  pipelines:
    clickstream:
      name: clickstream
      catalog: ${var.catalog_name}
      target: ${resources.schemas.raw.name}
      channel: CURRENT
      serverless: true
      configuration:
        raw_data_path: /Volumes/${var.catalog_name}/${resources.schemas.raw.name}/${resources.volumes.landing.name}
      libraries:
        - notebook:
            path: ../src/dlt/transformations/bronze.py
        - notebook:
            path: ../src/dlt/transformations/silver.py
        - notebook:
            path: ../src/dlt/transformations/gold.py
        - notebook:
            path: ../src/dlt/transformations/star_schema.py
