resources:
  pipelines:
    clickstream:
      name: clickstream
      catalog: ${var.catalog_name}
      target: ${resources.schemas.raw.name}
      channel: CURRENT
      serverless: true
      configuration:
        raw_data_path: /Volumes/${var.catalog_name}/${resources.schemas.raw.name}/${resources.volumes.landing.name}
      libraries:
        - notebook:
            path: ../src/dlt/bronze.py
        - notebook:
            path: ../src/dlt/silver.py
        - notebook:
            path: ../src/dlt/gold.py
        - notebook:
            path: ../src/dlt/star_schema.py
